"""empty message

Revision ID: 2954dc2f2bd7
Revises: 
Create Date: 2022-01-27 13:17:44.257421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2954dc2f2bd7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('costumer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('birthdate', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('init_time_scheduled', sa.String(), nullable=True),
    sa.Column('final_time_scheduled', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_costumer_cpf'), 'costumer', ['cpf'], unique=True)
    op.create_index(op.f('ix_costumer_email'), 'costumer', ['email'], unique=True)
    op.create_table('employee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('birthdate', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_cpf'), 'employee', ['cpf'], unique=True)
    op.create_index(op.f('ix_employee_email'), 'employee', ['email'], unique=True)
    op.create_table('product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('valid_through', sa.String(), nullable=True),
    sa.Column('lastModifiedByCpf', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_index(op.f('ix_employee_email'), table_name='employee')
    op.drop_index(op.f('ix_employee_cpf'), table_name='employee')
    op.drop_table('employee')
    op.drop_index(op.f('ix_costumer_email'), table_name='costumer')
    op.drop_index(op.f('ix_costumer_cpf'), table_name='costumer')
    op.drop_table('costumer')
    # ### end Alembic commands ###
