"""empty message

Revision ID: bcfcd36f4574
Revises: 3419616d2b9d
Create Date: 2022-01-26 13:18:40.680195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcfcd36f4574'
down_revision = '3419616d2b9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('lastModifiedByCpf', sa.String(), nullable=True))
    op.drop_column('product', 'lastModifiedBy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('lastModifiedBy', sa.VARCHAR(), nullable=True))
    op.drop_column('product', 'lastModifiedByCpf')
    # ### end Alembic commands ###
